# Generated by Django 5.1.5 on 2025-04-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
