# Generated by Django 5.1.5 on 2025-04-15 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_delete_adminprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form1_data', models.JSONField(blank=True, default=dict)),
                ('form2_data', models.JSONField(blank=True, default=dict)),
                ('form3_data', models.JSONField(blank=True, default=dict)),
                ('form4_data', models.JSONField(blank=True, default=dict)),
                ('form5_data', models.JSONField(blank=True, default=dict)),
                ('form6_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
