# Generated by Django 5.1.5 on 2025-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
