# Generated by Django 5.1.5 on 2025-04-24 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_taskassignment_delete_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='additional',
            new_name='additional_instructions',
        ),
        migrations.RenameField(
            model_name='taskassignment',
            old_name='assigned_date',
            new_name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='tanda',
            field=models.PositiveIntegerField(),
        ),
    ]
