# Generated by Django 5.1.5 on 2025-04-24 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_additional_taskassignment_additional_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='formdata',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_data', to='crm.taskassignment'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='tanda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
