# Generated by Django 5.1.5 on 2025-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='form7_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
